#' @title adults_06
#' @description Variables of adult survey of the ENSE 2006/07
#' @format A data frame with 29478 rows and 619 variables:
#' \describe{
#'   \item{\code{NIVEL}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CCAA}}{character COLUMN_DESCRIPTION}
#'   \item{\code{PROV *}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{ESTRATO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{SECCION}}{character COLUMN_DESCRIPTION}
#'   \item{\code{SECC_DC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{NIDENTIF}}{character COLUMN_DESCRIPTION}
#'   \item{\code{AÑO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{TRIM *}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{NORDEN}}{character COLUMN_DESCRIPTION}
#'   \item{\code{EDAD}}{character COLUMN_DESCRIPTION}
#'   \item{\code{SEXO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P3_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P3_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P3_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P5_0_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P5_0_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P5_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P5_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P5_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A3_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A3_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A4_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A4_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A6_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A6_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A7_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A7_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A9_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A9_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A10_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A10_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A11_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A11_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A12_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A12_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_1C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_1D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_2C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_2D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_3C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_3D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_4C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_4D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_5C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_5D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_6C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_6D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_7C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_7D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_8B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_8C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_8D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_9C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_9D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_10A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_10B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_10C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_10D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_11A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_11B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_11C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_11D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_12A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_12B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_12C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_12D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_13A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_13B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_13C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_13D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_14A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_14B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_14C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_14D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_15B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_15C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_15D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_16A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_16B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_16C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_16D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_17A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_17B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_17C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_17D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_18A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_18B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_18C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_18D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_19A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_19B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_19C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_19D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_20A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_20B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_20C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_20D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_21A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_21B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_21C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_21D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_22A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_22B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_22C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_22D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_23A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_23B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_23C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_23D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_24A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_24B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_24C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_24D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_25A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_25B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_25C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_25D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_26A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_26B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_26C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_26D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_27A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_27B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_27C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_27D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_28A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_28LI}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B15_28B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_28C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_28D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_29A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_29LI}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B15_29B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_29C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B15_29D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C18_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C18_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_3B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C18_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_4B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C18_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_5B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C18_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_6B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C18_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_7B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C18_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C18_8B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C21_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C21_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C21_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C21_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C21_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D22_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D22_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{D23_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D23_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{D24_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_8B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_10A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_10B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_11A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_11B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_12A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_12B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_13A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_13B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_14A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_14B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_15B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_16A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_16B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_17A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_17B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_18A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_18B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_19A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D24_19B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_8B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_10A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_10B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_11A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_11B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_12A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_12B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_13A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_13B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_14A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_14B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_15B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_16A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_16B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_17A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_17B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_18A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_18B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_19A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_19B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_20A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_20B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_21A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E25_22A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F26_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F27_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_29_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_29_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_29_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_30}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_31}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_32}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_33}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_34}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_35_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_35_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_35_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_36_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_36_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_36_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_37}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_38}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_1C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_2C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_3B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_3C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_4B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_4C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_5B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_5C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_6B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_39_6C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_40_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_40_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_40_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_40_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_40_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_40_3B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G2_41}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_42}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G3_43_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_44_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_44_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G4_44_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G4_44_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_45_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_46}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G4_47_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_48}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_49}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G5_50}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G5_51}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_52}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_53}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G5_54}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_55}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_56}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_57}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_58}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G5_59}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G6_60}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G6_61}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G6_62_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G6_62_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G6_62_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G6_63_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G6_63_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G6_63_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G6_64_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G6_64_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G6_65}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G6_66}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_67}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_68_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_68_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_68_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_69}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_70}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_71}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_72_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_72_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_72_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_73}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_74}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_75}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_76_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_76_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_77_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_77_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_77_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_77_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_77_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_77_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_77_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_77LIT}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_78_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_78_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_78_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H1_79_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_79_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_80_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H1_80_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_81}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_82}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_83}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_1C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_2C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_3B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_3C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_4B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_4C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_5B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_5C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_6B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_84_6C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H2_85_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_85_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_85_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_85_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_85_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_85_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H2_86}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H3_87}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H3_88}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_89_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_89_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_89_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_90}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_91}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_92}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_93}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H3_94_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H3_94_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H3_94_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H4_95_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_95_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_95_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_95_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_95_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_95_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_96_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_97}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H4_98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I1_99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I1_100}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I1_101}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I1_102}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I1_103}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I1_104}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I2_105}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I3_106_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_106}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_107}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_108}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_109}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_110}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_111}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_112_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_113}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_114}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_115}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_116}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I3_117}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_118_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_118_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_119_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_119_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_120_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_120_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_121_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I4_121_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J122_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J122}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J123_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J123}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J124}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J125_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J125_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J125_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J125_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J125_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J126}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_1C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_1D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_1E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_1F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_2C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_2D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_2E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_2F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_3C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_3D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_3E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_3F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_4B}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{J127_4C}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{J127_4D}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{J127_4E}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{J127_4F}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{J127_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_5C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_5D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_5E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_5F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_6C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_6D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_6E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J127_6F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L1_128}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L1_129}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L1_130}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L2_131}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L2_132}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L2_133}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L2_134}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M135_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M136_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M136_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M136_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M136_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M136_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N137}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N138}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N139}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N140_27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{FACTOR}}{character COLUMN_DESCRIPTION}
#'   \item{\code{TMUNI}}{double COLUMN_DESCRIPTION}
#'   \item{\code{SPCLASE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASCLASE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASRELACTI}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASSITUPRO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASSALMENT}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ASDEPFUN1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASDEPFUN2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASDEPFUN3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASAPSOCIAL}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASFUNFAMI}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ASIMC}}{double COLUMN_DESCRIPTION}
#'}
#' @details DETAILS
"adults_06"
