#' @title adults_19
#' @description Variables of adult survey of the ENSE 2017/19
#' @format A data frame with 23089 rows and 455 variables:
#' \describe{
#'   \item{\code{CCAA}}{factor: provides region}
#'   \item{\code{IDENTHOGAR}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A7_2a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{SEXOa}}{double COLUMN_DESCRIPTION}
#'   \item{\code{EDADa}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ACTIVa}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_2b}}{character COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_3b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{PROXY_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E1_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E2_1a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E2_1b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E2_1c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E2_1d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{E4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E4b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{NIVEST}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F8_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F9_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F13}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F14a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F14b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F17}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F18a_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F18b_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F19a_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F19b_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_26}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_29}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25a_32}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25b_32}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25c_32}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H26_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H26_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H26_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H27}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I28_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I28_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{I29_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I29_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K32}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K33}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K34}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K35}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K36}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K37}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K38}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K38a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L39_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L39_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L39_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L39_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L39_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L40}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L41}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L42_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L42_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L42_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L42_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L42_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L42_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L42_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L43}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L44}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L45}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L46}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M47b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N48}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N49}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N50}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N51}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N52}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N53}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N54}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N55_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N55_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N55_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N56_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N56_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N56_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N57}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N58_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N58_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N58_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N59}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60a_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60a_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60a_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N60a_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N61_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N61_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N61_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N61_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N61_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N62}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N62b}}{character COLUMN_DESCRIPTION}
#'   \item{\code{N63_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N63_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N64}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N65_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O66}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O67}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O69}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O70}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O71}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O72}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O73}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O74}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O75}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O76}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O77}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O78}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O79}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O80_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O80_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O80_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O81_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O81_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O81_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O82_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O82_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{O83}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{O84_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P85}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P86}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_1a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_1b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_2a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_2b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_3a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_3b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_4a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_4b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_5a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_5b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_6a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_6b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_7a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_7b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_8a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_8b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_9a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_9b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_10a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_10b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_11a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_11b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_12a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_12b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_13a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_13b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_14a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_14b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_15a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_15b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_16a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_16b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_17a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_17b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_18a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_18b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_19a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_19b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_20a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_20b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_21a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_21b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_22a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_22b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_23a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P87_23b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q88}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q89}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q90}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q91}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q92}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q93}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q94}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q95}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q96}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q97}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q98}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q99}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q100}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q101}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q102}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q103}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q104}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Q105}}{double COLUMN_DESCRIPTION}
#'   \item{\code{R106}}{double COLUMN_DESCRIPTION}
#'   \item{\code{R107}}{double COLUMN_DESCRIPTION}
#'   \item{\code{R108_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{R108_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{R108_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{R108_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{S109}}{double COLUMN_DESCRIPTION}
#'   \item{\code{S110}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T111}}{double COLUMN_DESCRIPTION}
#'   \item{\code{T112}}{double COLUMN_DESCRIPTION}
#'   \item{\code{T113}}{double COLUMN_DESCRIPTION}
#'   \item{\code{T114_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T114_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T115}}{double COLUMN_DESCRIPTION}
#'   \item{\code{T116_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T116_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T117}}{double COLUMN_DESCRIPTION}
#'   \item{\code{T118_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T118_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T119_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{T119_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{U120_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_1a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{U120_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_7a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{U120_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120_15a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{U120FZ}}{double COLUMN_DESCRIPTION}
#'   \item{\code{U120CANTFZ}}{character COLUMN_DESCRIPTION}
#'   \item{\code{U2_120F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V121}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V122}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V123}}{character COLUMN_DESCRIPTION}
#'   \item{\code{V124}}{character COLUMN_DESCRIPTION}
#'   \item{\code{V125}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V126}}{double COLUMN_DESCRIPTION}
#'   \item{\code{W127}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer}}{double COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer_5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer_6}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Cer_7}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin}}{double COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin_5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin_6}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vin_7}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut}}{double COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut_5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut_6}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Vermut_7}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic}}{double COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic_5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic_6}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Lic_7}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb}}{double COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb_5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb_6}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Comb_7}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra}}{double COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra_5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra_6}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W128Sidra_7}}{character COLUMN_DESCRIPTION}
#'   \item{\code{W129}}{character COLUMN_DESCRIPTION}
#'   \item{\code{X130_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{X130_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Y133}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Y134}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Y135}}{double COLUMN_DESCRIPTION}
#'   \item{\code{FACTORADULTO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CLASE_PR}}{double COLUMN_DESCRIPTION}
#'   \item{\code{IMCa}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CMD1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{CMD2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{CMD3}}{character COLUMN_DESCRIPTION}
#'}
#' @NA NULL
"adults_19"
