#' @title children_06
#' @description Variables of children survey of the ENSE 2006/07
#' @format A data frame with 9122 rows and 350 variables:
#' \describe{
#'   \item{\code{NIVEL}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CCAA}}{character COLUMN_DESCRIPTION}
#'   \item{\code{PROV}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{ESTRATO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{SECCION}}{character COLUMN_DESCRIPTION}
#'   \item{\code{SECC_DC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{NIDENTIF}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A??O}}{double COLUMN_DESCRIPTION}
#'   \item{\code{TRIM}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{NORDEN}}{double COLUMN_DESCRIPTION}
#'   \item{\code{EDAD}}{character COLUMN_DESCRIPTION}
#'   \item{\code{EDADMES}}{character COLUMN_DESCRIPTION}
#'   \item{\code{SEXO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P3_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P3_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P3_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P4_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P4_0_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{P4_0_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P4_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{P4_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_1C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_1D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_2C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_2D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_3C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_3D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_4C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_4D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_5C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_5D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_6C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_6D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_7C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_7D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_8LIT}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A2_8B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_8C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_8D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_9LIT}}{character COLUMN_DESCRIPTION}
#'   \item{\code{A2_9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_9C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_9D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B5_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B5_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_3B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B5_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_4B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B5_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_5B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B5_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_6B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B5_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_7B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B5_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_8B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B8_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B8_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B8_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B8_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B8_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C12_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C12_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{C13_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_8B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_10A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_10B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_11A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_11B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_12A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_12B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_13A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_13B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_14A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C13_14B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_4B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_5B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_6B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_7A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_7B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_8A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_8B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_9A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_9B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_10A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_10B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_11A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_11B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_12A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_12B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_13A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_13B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_14A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D14_15A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{E15_25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_16_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_16_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_16_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_17}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_18}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_19}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_20}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_22_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_22_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_22_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_23_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_23_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_23_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_1C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_2C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_3B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_3C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_4A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_4B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_4C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_5A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_5B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_5C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_6A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_6B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_26_6C}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_27_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_27_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F1_27_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F1_27_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F2_28}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F2_29}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F3_30_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_31_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_31_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F4_31_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F4_31_4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_32_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_33}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_34}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_35}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_36_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_36_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_36_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_36_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F4_36_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_37}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_38}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F5_39}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F5_40}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_41}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_42}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F5_43}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_44}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_45}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_46}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_47}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F5_48}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6_49}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F6_50}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6_51_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F6_51_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F6_51_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F6_52_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6_52_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6_52_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6_53_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6_53_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F6_54}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F6_55}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_56}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_57}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_58_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_58}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_59_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_59_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_59_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_59_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_60}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_61_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_61_1B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_61_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G1_61_2B}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_62_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_63}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_64_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G2_64_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G2_65}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_66_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_66_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G2_67}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_68_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G2_68_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G1_69}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_70_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_70_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_70_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_70_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_70_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_70_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_71_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_72}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G2_73}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H74_0}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H75}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H76}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H77_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H77_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H78}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H79}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I80}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_1A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_1B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_1C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_1D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_1E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_2A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_2B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_2C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_2D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_2E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_3A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_3B}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_3C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_3D}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I81_3E}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K93}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K94}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K95}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K96}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K97}}{double COLUMN_DESCRIPTION}
#'   \item{\code{FACTOR}}{character COLUMN_DESCRIPTION}
#'   \item{\code{TMUNI}}{double COLUMN_DESCRIPTION}
#'   \item{\code{SPCLASE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{MSCALVIDA}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSSALMENT1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSSALMENT2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSSALMENT3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSSALMENT4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSSALMENT5}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSIMC}}{double COLUMN_DESCRIPTION}
#'}
#' @details DETAILS
"children_06"
