#' @title children_12
#' @description Dataset Children Survey ENSE 2011/12
#' @format A data frame with 5495 rows and 271 variables:
#' \describe{
#'   \item{\code{CCAA}}{character COLUMN_DESCRIPTION}
#'   \item{\code{IDENTHOGAR}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ESTRATO}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A7_2m}}{double COLUMN_DESCRIPTION}
#'   \item{\code{SEXOm}}{double COLUMN_DESCRIPTION}
#'   \item{\code{EDADm}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Informante_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Informante_1a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Informante_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Informante_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Informante_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A1_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PAISEXT}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{A2_1a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_1b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_1c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{A2_1d}}{double COLUMN_DESCRIPTION}
#'   \item{\code{NACEXT}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{A3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{B4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_1a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_1b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_1c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_2a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_2b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_2c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_3a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_3b}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{B5_3c}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{B5_4a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_4b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_4c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_5a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_5b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_5c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_6a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_6b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_6c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_7a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_7b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_7c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_8a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_8b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_8c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_9_1b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_9_1c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_9_2b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_9_2c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_9_3b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B5_9_3c}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{B7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{C11_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D12_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D12_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{D13_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{D13_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MCALVIDA}}{character COLUMN_DESCRIPTION}
#'   \item{\code{F15_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_16}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_17}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_18}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_20}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_22}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_23}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{F15_25}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G16_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G16_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G16_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G17_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G17_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G18_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G18_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G19}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G20}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G21}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G22_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G22_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G22_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G23_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G23_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G23_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G24}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G25_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G26_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G26_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G26_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G26_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G27_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G27_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G27_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G27_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G28_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G28_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{G29_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G29_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G30}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G31}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G32_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G32_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G32_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G32_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{G32_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H33}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H34}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H35}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H36}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H37}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H38}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H39}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H40}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H41}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H42}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H43}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H44}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H45}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H46_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H46_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H46_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H47_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H47_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H47_3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H48_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H48_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{H49}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H50}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H51}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H52}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{H53_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I54}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_1a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_1b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_2a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_2b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_3a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_3b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_4a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_4b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_5a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_5b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_6a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_6b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_7a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_7b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_8a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_8b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_9a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_9b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_10a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_10b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_11a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_11b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_12a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_12b}}{logical COLUMN_DESCRIPTION}
#'   \item{\code{I55_13a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I55_13b}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I56_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{I56_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{J57}}{character COLUMN_DESCRIPTION}
#'   \item{\code{J58}}{character COLUMN_DESCRIPTION}
#'   \item{\code{J59}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K60}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K61}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K62_1a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K62_1b}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K62_2a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K62_2b}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K63_1a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K63_1b}}{character COLUMN_DESCRIPTION}
#'   \item{\code{K63_2a}}{double COLUMN_DESCRIPTION}
#'   \item{\code{K63_2b}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L64}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L65_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L65_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L66}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L67_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L67_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L68}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L69_1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L69_2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L70}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L71_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L71_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L71_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L71_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L71_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L71_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L71_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_1a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L72_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_6}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_7}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_7a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L72_8}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_9}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_10}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_11}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_12}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_13}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_14}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L72_15a}}{character COLUMN_DESCRIPTION}
#'   \item{\code{L73}}{double COLUMN_DESCRIPTION}
#'   \item{\code{L74}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M75}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M76_1}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M76_2}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M76_3}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M76_4}}{double COLUMN_DESCRIPTION}
#'   \item{\code{M76_5}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N77}}{double COLUMN_DESCRIPTION}
#'   \item{\code{N78}}{double COLUMN_DESCRIPTION}
#'   \item{\code{FACTORMENOR}}{character COLUMN_DESCRIPTION}
#'   \item{\code{CLASE_PR}}{double COLUMN_DESCRIPTION}
#'   \item{\code{IMCm}}{double COLUMN_DESCRIPTION}
#'   \item{\code{MSALMENT1}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSALMENT2}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSALMENT3}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSALMENT4}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MSALMENT5}}{character COLUMN_DESCRIPTION}
#'}
#' @details DETAILS
"children_12"
